name: Master


on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and push to local registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: docker/deb.dockerfile
          tags: localhost:5000/chip-ubuntu:latest, localhost:5000/chip-ubuntu:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha
      
      - name: Get binary from docker image
        run: docker run --entrypoint cat localhost:5000/chip-ubuntu:latest /root/.local/bin/chip > ./chip

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: chip-ubuntu
          path: ./chip


